/*
 Write a Java program to implement the SHA-1 algorithm 
 for encrypting and decrypting a message.
 */

import java.math.*;
import java.security.*;

public class SHAExp 
{
    public static String encrypt(String input)
    {
        try
        {
            //SHA-1 (Message Digest)
            MessageDigest md = MessageDigest.getInstance("SHA-1");
            byte[] Digest = md.digest(input.getBytes());

            BigInteger n = new BigInteger(1,Digest);
            String hashtext = n.toString(16);
            while(hashtext.length()<32)
            {
                hashtext="0"+hashtext;
            }
            return hashtext;
        }
        catch(NoSuchAlgorithmException e)
        {
            throw new RuntimeException(e);
        }
    }
    public static void main(String[] args) throws NoSuchAlgorithmException
    {
        String s1="Hello! World, Namaskara!, Namaste!, Vanakkam!, Namaskaram!";
        String s2="The earth revolves around the sun";
        System.out.println("\nHash Code Generated by SHA-1 for: ");
        System.out.println(s1+":"+encrypt(s1));
        System.out.println(s2+":"+encrypt(s2));
        System.out.println();
    }    
}
